#!/usr/bin/env bash
# 🧱 C13B0 — Global Ion Research Writer
# MODE: SAFE / ADDITIVE / NON-DESTRUCTIVE
# Writes a unique ion research article into every repo

set -euo pipefail

USER="${GITHUB_USER:-www-infinity}"
BASE="$HOME/c13b0_ion_research_sweep"
STAMP=$(date -u +%Y%m%d_%H%M%S)

mkdir -p "$BASE"
cd "$BASE"

echo "🧱 Starting Global ION Research Writer — $STAMP"

hash_seed() {
  local s="$1"
  if command -v sha256sum >/dev/null 2>&1; then
    echo -n "$s" | sha256sum | awk '{print $1}' | cut -c1-8
  else
    echo -n "$s" | shasum -a 256 | awk '{print $1}' | cut -c1-8
  fi
}

THEME_TITLE=(
  "Ions as the hidden currency of charge"
  "Electrochemistry: ions driving batteries and plating"
  "Ions in semiconductors: doping, defects, and drift"
  "Plasma and ionization: when gas becomes circuitry"
  "Biological ions: membranes, signals, and gradients"
  "Corrosion and passivation: ions rewriting metal"
  "Water, salts, and ionic strength: chemistry of solutions"
  "Ionic motion in materials: solid electrolytes and sensors"
  "Ion beams and mass spectrometry: separating matter by charge"
  "Atmospheric ions: lightning, aerosols, and charge balance"
  "Ions in energy storage: supercaps, redox flow, and beyond"
  "Ionic selectivity: sieves, membranes, and filtration"
)

THEME_FOCUS=(
  "core definitions, charge balance, and why ions matter in every electrical system"
  "redox, electrode potentials, electrolyte design, and real-world constraints"
  "dopants, ionic contamination, mobile ions, and device stability"
  "ionization energy, plasmas, sheaths, and controllable discharge regimes"
  "Na+, K+, Ca2+, Cl− in signaling, nerve impulses, and homeostasis"
  "galvanic couples, chloride attack, oxide layers, and prevention strategies"
  "dissociation, hydration shells, activity vs concentration, and conductivity"
  "diffusion, migration, intercalation, and solid-state conduction mechanisms"
  "ion sources, time-of-flight, quadrupoles, isotopes, and practical measurement"
  "ion production, cosmic rays, thundercloud fields, and aerosol nucleation"
  "tradeoffs among energy density, power, cycle life, safety, and chemistry"
  "permselectivity, pore size, Donnan exclusion, and practical purification"
)

REPOS=$(gh repo list "$USER" --limit 2000 --json name -q '.[].name')

for REPO in $REPOS; do
  echo ""
  echo "🧠 Repo: $REPO"

  if [ -d "$REPO" ]; then
    cd "$REPO"
    git pull --quiet >/dev/null 2>&1 || true
  else
    git clone "https://github.com/$USER/$REPO.git" --quiet >/dev/null 2>&1 || { echo "⚠️ clone failed"; continue; }
    cd "$REPO"
  fi

  mkdir -p RESEARCH
  FILE="RESEARCH/ion_research_${REPO}.md"

  if [ -f "$FILE" ]; then
    echo "⏭️  Exists — skipping: $FILE"
    cd ..
    continue
  fi

  KEYWORDS=$(
    (
      echo "$REPO"
      find . -maxdepth 3 -type f 2>/dev/null | sed 's|^\./||' | tr '/._-' ' '
    ) | tr ' ' '\n' | sort -u | head -n 40 | tr '\n' ', '
  )

  SEEDHEX=$(hash_seed "$REPO")
  SEEDDEC=$((16#${SEEDHEX}))
  IDX=$((SEEDDEC % ${#THEME_TITLE[@]}))
  TITLE="${THEME_TITLE[$IDX]}"
  FOCUS="${THEME_FOCUS[$IDX]}"

  echo "✍️  Writing: $FILE (theme: $TITLE)"

  cat <<DOC > "$FILE"
# ⚡ Ion Research Brief — $REPO

**Generated by:** 🧱 C13B0 Global Ion Research Writer
**Timestamp (UTC):** $STAMP
**Repo-anchored seed:** $SEEDHEX
**Theme:** $TITLE

---

## 1) Why ions belong in *this* repo

**Repo anchor:** \`$REPO\`

**Local keyword fingerprint:**
$KEYWORDS

---

## 2) Ion fundamentals

An **ion** is an atom or molecule with a **net electric charge** because it has lost or gained electrons.

- **Cations** (positive): fewer electrons than protons (e.g., Na⁺, Ca²⁺)
- **Anions** (negative): more electrons than protons (e.g., Cl⁻, SO₄²⁻)

### Transport modes
- **Diffusion** (concentration gradient)
- **Migration** (electric field)
- **Convection** (fluid flow)

---

## 3) Theme focus: $TITLE

**Focus:** $FOCUS

### Interfaces are where the action happens

- electrode ↔ electrolyte
- membrane ↔ fluid
- oxide ↔ metal
- pore surface ↔ solution

At interfaces you see **double layers**, **overpotentials**, **selectivity**, and **adsorption**.

---

## 4) Practical: what to measure, what to control

- **Conductivity** — bulk ionic content proxy
- **pH / ORP** — reaction direction / redox environment
- **EIS** — charge transfer vs diffusion limits
- **Ion-selective probes** — Na⁺, K⁺, Ca²⁺, Cl⁻

---

## 5) Closing

Ions are the bridge between matter and electricity, chemistry and computation.

🧱 Built to persist
🧱 Built to connect
🧱 Built to grow

— **C13B0 Ion Research Engine**
DOC

  git add RESEARCH >/dev/null 2>&1 || true
  git commit -m "⚡ Add ion research article (C13B0)" >/dev/null 2>&1 || true
  git push >/dev/null 2>&1 || true

  cd ..
done

echo ""
echo "🧱 Global Ion Research Writer COMPLETE"
