#!/usr/bin/env bash
# 🧱 C13B0 Cart G — Promote Import to Web Page
# USER: www-infinity
# PURPOSE: Turn imported content into visible pages

set -euo pipefail

USER="${GITHUB_USER:-www-infinity}"
TARGET_REPO="infinity-imports"

STAMP="$(date -u +%Y%m%d_%H%M%S)"
WORKDIR="$HOME/.c13b0_G_$STAMP"

echo "🧱 Cart G — Promote Import to Page"
echo "👤 $USER"
echo "📦 Repo: $TARGET_REPO"
echo "🕒 $STAMP"
echo

cd "$HOME" || exit 0

if ! gh repo view "$USER/$TARGET_REPO" >/dev/null 2>&1; then
  echo "❌ Repo $TARGET_REPO does not exist"
  exit 0
fi

rm -rf "$WORKDIR"
git clone "https://github.com/$USER/$TARGET_REPO.git" "$WORKDIR" >/dev/null 2>&1 || exit 0
cd "$WORKDIR" || exit 0

mkdir -p pages imports

LATEST_IMPORT="$(ls -1 imports/import_*.txt 2>/dev/null | sort | tail -n 1)"

if [[ -z "$LATEST_IMPORT" ]]; then
  echo "❌ No imports found — run Cart F3 first"
  exit 0
fi

BASENAME="$(basename "$LATEST_IMPORT" .txt)"
PAGE="pages/${BASENAME}.html"

echo "🔵 Promoting $LATEST_IMPORT → $PAGE"

cat > "$PAGE" <<EOF
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>$BASENAME</title>
<style>
body{font-family:system-ui;background:#0b1220;color:#e5e7eb;padding:20px}
pre{background:#111827;padding:16px;border-radius:8px;border:1px solid #374151;white-space:pre-wrap}
</style>
</head>
<body>
<h1>🔵 Imported Content</h1>
<pre>
$(cat "$LATEST_IMPORT")
</pre>
<p style="color:#9ca3af">Generated by Cart G — $STAMP</p>
</body>
</html>
EOF

if [[ ! -f index.html ]]; then
  cat > index.html <<'IDX'
<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><title>Infinity Imports</title>
<style>body{font-family:system-ui;background:#0b1220;color:#e5e7eb;padding:20px}
a{color:#60a5fa}li{margin:6px 0}</style>
</head>
<body>
<h1>🌐 Infinity Imports</h1>
<ul id="list"></ul>
</body>
</html>
IDX
fi

if ! grep -q "$PAGE" index.html 2>/dev/null; then
  sed -i "s|</ul>|  <li><a href=\"$PAGE\">$BASENAME</a></li>\n</ul>|" index.html
fi

git add pages index.html
git commit -m "🌐 Promote import to web page ($BASENAME)" >/dev/null 2>&1
git push >/dev/null 2>&1

echo ""
echo "✅ Import promoted to web page"
echo "🌐 https://$USER.github.io/$TARGET_REPO/$PAGE"
echo "🧱 Cart G COMPLETE"
