#!/usr/bin/env bash
# slot_machine.sh — Slot Machine Self-Builder
# Each "spin" generates a new cartridge directory with a run script.
# Usage: ./slot_machine.sh [output_dir]

set -euo pipefail

SYMBOLS=("🍄" "⭐" "👑" "💲" "🧱" "🔱" "🎰")
SPIN_COUNT=${#SYMBOLS[@]}

spin() {
    echo "${SYMBOLS[$((RANDOM % SPIN_COUNT))]}"
}

STAMP=$(date -u +%Y%m%d_%H%M%S)
DATE_HUMAN=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
REEL1=$(spin)
REEL2=$(spin)
REEL3=$(spin)

echo "🎰 SLOT MACHINE SPINNING..."
echo "  [ $REEL1 | $REEL2 | $REEL3 ]"

BASE="${1:-./cartridges}"
CART_NAME="cart_${STAMP}"
CART_DIR="$BASE/$CART_NAME"

mkdir -p "$CART_DIR"

cat > "$CART_DIR/run.sh" <<EOF
#!/usr/bin/env bash
# Generated cartridge: $CART_NAME
# Spin result: $REEL1 $REEL2 $REEL3
echo "💲 Cartridge running: $CART_NAME"
echo "Spin: $REEL1 $REEL2 $REEL3"
echo "Path: \$(pwd)"
EOF
chmod +x "$CART_DIR/run.sh"

cat > "$CART_DIR/README.md" <<EOF
# $CART_NAME

Generated by slot_machine.sh on $DATE_HUMAN

## Spin Result
| Reel 1 | Reel 2 | Reel 3 |
|--------|--------|--------|
| $REEL1 | $REEL2 | $REEL3 |
EOF

echo "✅ New cartridge created: $CART_DIR"
echo "   Run it: bash $CART_DIR/run.sh"
